package com.ddd.Shipment.mybatis.dao;

import com.ddd.Shipment.mybatis.model.Address;
import java.util.List;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ADDRESS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ADDRESS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ADDRESS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    Address selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ADDRESS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    List<Address> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ADDRESS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    int updateByPrimaryKey(Address record);
}