package com.ddd.Shipment.mybatis.dao;

import com.ddd.Shipment.mybatis.model.Orders;
import java.util.List;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORDERS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORDERS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORDERS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    Orders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORDERS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    List<Orders> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORDERS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    int updateByPrimaryKey(Orders record);
}