package com.ddd.Shipment.mybatis.dao;

import com.ddd.Shipment.mybatis.model.ParcelInfo;
import java.util.List;

public interface ParcelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PARCELINFO
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PARCELINFO
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    int insert(ParcelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PARCELINFO
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    ParcelInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PARCELINFO
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    List<ParcelInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PARCELINFO
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    int updateByPrimaryKey(ParcelInfo record);
}