package com.ddd.Shipment.mybatis.dao;

import com.ddd.Shipment.mybatis.model.ShipmentEvent;
import java.util.List;

public interface ShipmentEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHIPMENTEVENT
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHIPMENTEVENT
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    int insert(ShipmentEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHIPMENTEVENT
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    ShipmentEvent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHIPMENTEVENT
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    List<ShipmentEvent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHIPMENTEVENT
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    int updateByPrimaryKey(ShipmentEvent record);
}