package com.ddd.Shipment.mybatis.model;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ADDRESS.ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ADDRESS.USER_ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ADDRESS.CITY
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ADDRESS.ADDRESS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ADDRESS.POSTAL_CODE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private String postalCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ADDRESS.ID
     *
     * @return the value of PUBLIC.ADDRESS.ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ADDRESS.ID
     *
     * @param id the value for PUBLIC.ADDRESS.ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ADDRESS.USER_ID
     *
     * @return the value of PUBLIC.ADDRESS.USER_ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ADDRESS.USER_ID
     *
     * @param userId the value for PUBLIC.ADDRESS.USER_ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ADDRESS.CITY
     *
     * @return the value of PUBLIC.ADDRESS.CITY
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ADDRESS.CITY
     *
     * @param city the value for PUBLIC.ADDRESS.CITY
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ADDRESS.ADDRESS
     *
     * @return the value of PUBLIC.ADDRESS.ADDRESS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ADDRESS.ADDRESS
     *
     * @param address the value for PUBLIC.ADDRESS.ADDRESS
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ADDRESS.POSTAL_CODE
     *
     * @return the value of PUBLIC.ADDRESS.POSTAL_CODE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ADDRESS.POSTAL_CODE
     *
     * @param postalCode the value for PUBLIC.ADDRESS.POSTAL_CODE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
}