package com.ddd.Shipment.mybatis.model;

public class ParcelInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PARCELINFO.ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PARCELINFO.SPEED_TYPE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private String speedType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PARCELINFO.SIZE_TYPE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private String sizeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PARCELINFO.FRAGILE_TYPE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private Short fragileType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PARCELINFO.ID
     *
     * @return the value of PUBLIC.PARCELINFO.ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PARCELINFO.ID
     *
     * @param id the value for PUBLIC.PARCELINFO.ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PARCELINFO.SPEED_TYPE
     *
     * @return the value of PUBLIC.PARCELINFO.SPEED_TYPE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public String getSpeedType() {
        return speedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PARCELINFO.SPEED_TYPE
     *
     * @param speedType the value for PUBLIC.PARCELINFO.SPEED_TYPE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setSpeedType(String speedType) {
        this.speedType = speedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PARCELINFO.SIZE_TYPE
     *
     * @return the value of PUBLIC.PARCELINFO.SIZE_TYPE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public String getSizeType() {
        return sizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PARCELINFO.SIZE_TYPE
     *
     * @param sizeType the value for PUBLIC.PARCELINFO.SIZE_TYPE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setSizeType(String sizeType) {
        this.sizeType = sizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PARCELINFO.FRAGILE_TYPE
     *
     * @return the value of PUBLIC.PARCELINFO.FRAGILE_TYPE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public Short getFragileType() {
        return fragileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PARCELINFO.FRAGILE_TYPE
     *
     * @param fragileType the value for PUBLIC.PARCELINFO.FRAGILE_TYPE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setFragileType(Short fragileType) {
        this.fragileType = fragileType;
    }
}