package com.ddd.Shipment.mybatis.model;

public class ShipmentEvent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHIPMENTEVENT.ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHIPMENTEVENT.ORDER_STATE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private String orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHIPMENTEVENT.CITY
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHIPMENTEVENT.DATE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHIPMENTEVENT.ORDER_ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHIPMENTEVENT.ID
     *
     * @return the value of PUBLIC.SHIPMENTEVENT.ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHIPMENTEVENT.ID
     *
     * @param id the value for PUBLIC.SHIPMENTEVENT.ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHIPMENTEVENT.ORDER_STATE
     *
     * @return the value of PUBLIC.SHIPMENTEVENT.ORDER_STATE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHIPMENTEVENT.ORDER_STATE
     *
     * @param orderState the value for PUBLIC.SHIPMENTEVENT.ORDER_STATE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHIPMENTEVENT.CITY
     *
     * @return the value of PUBLIC.SHIPMENTEVENT.CITY
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHIPMENTEVENT.CITY
     *
     * @param city the value for PUBLIC.SHIPMENTEVENT.CITY
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHIPMENTEVENT.DATE
     *
     * @return the value of PUBLIC.SHIPMENTEVENT.DATE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHIPMENTEVENT.DATE
     *
     * @param date the value for PUBLIC.SHIPMENTEVENT.DATE
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHIPMENTEVENT.ORDER_ID
     *
     * @return the value of PUBLIC.SHIPMENTEVENT.ORDER_ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHIPMENTEVENT.ORDER_ID
     *
     * @param orderId the value for PUBLIC.SHIPMENTEVENT.ORDER_ID
     *
     * @mbg.generated Sat May 08 13:31:26 EEST 2021
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}