package com.ddd.Shipment.mybatis.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.ID
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.NAME
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.EMAIL
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.USERNAME
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.PASSWORD
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.NUMBER
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.SESSION_TOKEN
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    private String sessionToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.ID
     *
     * @return the value of PUBLIC.USER.ID
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.ID
     *
     * @param id the value for PUBLIC.USER.ID
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.NAME
     *
     * @return the value of PUBLIC.USER.NAME
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.NAME
     *
     * @param name the value for PUBLIC.USER.NAME
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.EMAIL
     *
     * @return the value of PUBLIC.USER.EMAIL
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.EMAIL
     *
     * @param email the value for PUBLIC.USER.EMAIL
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.USERNAME
     *
     * @return the value of PUBLIC.USER.USERNAME
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.USERNAME
     *
     * @param username the value for PUBLIC.USER.USERNAME
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.PASSWORD
     *
     * @return the value of PUBLIC.USER.PASSWORD
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.PASSWORD
     *
     * @param password the value for PUBLIC.USER.PASSWORD
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.NUMBER
     *
     * @return the value of PUBLIC.USER.NUMBER
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.NUMBER
     *
     * @param number the value for PUBLIC.USER.NUMBER
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.SESSION_TOKEN
     *
     * @return the value of PUBLIC.USER.SESSION_TOKEN
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public String getSessionToken() {
        return sessionToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.SESSION_TOKEN
     *
     * @param sessionToken the value for PUBLIC.USER.SESSION_TOKEN
     *
     * @mbg.generated Sat May 08 13:31:25 EEST 2021
     */
    public void setSessionToken(String sessionToken) {
        this.sessionToken = sessionToken;
    }
}